# Site settings
title: Website for Northwood United Methodist Church in Esko Minnesota
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Website for Northwood United Methodist Church (NUMC) in Esko Minnesota, a small church with a BIG heart.
  Come join us for Sunday worship at 9:00 AM
baseurl: "/eskomethodist" # the subpath for your site

# Build settings
markdown: kramdown
